# REST API request template
# Fill in the blank values below before sending requests.

# For example http://localhost:9093
@baseUrl = http://localhost:9093

@adminFirstName = Admin
@adminLastName = User
@adminEmail = admin@example.com
@adminPassword = Admin1234!

@userUsername = testuser
@userEmail = user@example.com
@userPassword = User1234!

### 1. Admin Section
### 1.1 Register Admin
# @name adminRegister
POST {{baseUrl}}/admin/auth/register-admin
Content-Type: application/json

{
  "firstname": "{{adminFirstName}}",
  "lastname": "{{adminLastName}}",
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "rememberMe": true
}

### 1.2 Admin Login
# @name adminLogin
POST {{baseUrl}}/admin/auth/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "rememberMe": true
}

### 1.3 Admin Forgot Password
# @name adminForgotPassword
POST {{baseUrl}}/admin/auth/forgot-password
Content-Type: application/json

{
  "email": "{{adminEmail}}"
}

### 1.4 Admin Profile
# @name adminProfile
GET {{baseUrl}}/admin/users/me
Authorization: Bearer {{adminLogin.response.body.$.data.token}}

### 2. User Section
### 2.1 User Register
# @name userRegister
POST {{baseUrl}}/api/auth/local/register
Content-Type: application/json

{
  "username": "{{userUsername}}",
  "email": "{{userEmail}}",
  "password": "{{userPassword}}"
}

### 2.2 User Login
# @name userLogin
POST {{baseUrl}}/api/auth/local
Content-Type: application/json

{
  "identifier": "{{userEmail}}",
  "password": "{{userPassword}}"
}

### 2.3 User Forgot Password
# @name userForgotPassword
POST {{baseUrl}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "{{userEmail}}"
}

### 2.4 User Profile
# @name userProfile
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{userLogin.response.body.$.jwt}}
