version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: 69-s3-db
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "54327:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-admin
    restart: always
    env_file:
      - ./admin/.env
    ports:
      - "8083:80"
    depends_on:
      - db

  app:
    image: prawee/strapi
    container_name: 69-s3-app
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "1337:1337"
    depends_on:
      - db

volumes:
  db_data: