version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "127.0.0.1:54327:5432"
    env_file:
      - ./db/.env

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-admin
    ports:
      - "8083:80"
    env_file:
      - ./admin/.env
    depends_on:
      - db

  app:
    image: prawee/strapi
    container_name: 69-s3-app
    ports:
      - "127.0.0.1:1337:1337"
    env_file:
      - ./app/.env
    depends_on:
      - db